//line grammar/lexer.go:2
//line grammar/lexer.l:33
package grammar

import (
    "fmt"
    "io"
    "log"
    "os"
    "math"
    "strconv"
    "strings"

    "github.com/CapacitorSet/yara-parser/data"
)

// Necessary types for flexgo
type YYtype interface{}
type YYcontext interface{}

// Global YYtext - each action sets this to the current yytext
var YYtext string

// Accumulators for gathering groups of tokens as text because text collection
// is like an "inclusive" start condition while the lexer requires "exclusive"
var (
    collect           bool  // condition text
    collectText       bool  // string/regex/etc text
    textBuilder       strings.Builder
)

  // This comment applies to the YY_USER_ACTION macro, which is having
  // a problem with comments...
  // For condition, the colons and whitespace will be collected in the
  // prefix and the right brace for the suffix. Use strings.TrimLeft/Right





//line grammar/lexer.go:42

// START OF SKELL ------------------------------------------------------
// A lexical scanner generated by flexgo

type Scanner struct {
	In   io.Reader
	Out  io.Writer
	Lineno int

	Filename      string
	Wrap          func(*Scanner) bool
	IsInteractive func(io.Reader) bool
	Context       YYcontext

	lastAcceptingState   int
	lastAcceptingCpos    int
	debug                bool
	start                int
	stateBuf             []int
	statePtr             int
	fullState            int
	fullMatch            int
	fullLp               int
	lp                   int
	lookingForTrailBegin int
	holdChar             byte
	cBufP                int
	didBufferSwitchOnEof bool
	textPtr              int
	nChars               int
	init                 bool
	moreFlag             bool
    moreLen              int

	// buffer
	inputFile    io.Reader
	chBuf        []byte // input buffer
	bufPos       int    // current position in input buffer
	bufSize      int
	bufNChars    int
	Interactive  bool
	atBol        int // 0 (false) or 1 (true)
	fillBuffer   bool
	bufferStatus int
}

func NewScanner() *Scanner {
	yy := Scanner{
		Lineno: 1,
		In:            os.Stdin,
		Out:           os.Stdout,
		Wrap:          func(yyy *Scanner) bool { return true },
		IsInteractive: func(file io.Reader) bool { return yyInteractiveDefault },
		bufSize:       yyBufSize,
		chBuf:         make([]byte, yyBufSize+2),
		start:         1,
		stateBuf:      make([]int, yyBufSize+2),
		atBol:         1,
		debug:         yyFlexDebug,
		fillBuffer:    true,
	}
	return &yy
}

func (yy *Scanner) NewFile() {
	yy.Restart(yy.In)
}

const yyEndOfBufferChar = 0

const yyBufSize = 32768

const (
	eobActEndOfFile    = 0
	eobActContinueScan = 1
	eobActLastMatch    = 2
)

const (
	yyBufferNew        = 0
	yyBufferNormal     = 1
	yyBufferEofPending = 2
)

// [1.0] the user's section 1 definitions and yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here
/* Begin user sect3 */
const yyFlexDebug = false

const yyInteractiveDefault = false
// SKEL ----------------------------------------------------------------

// [1.5] DFA------------------------------------------------------------
// SKEL ----------------------------------------------------------------

// [4.0] data tables for the DFA go here -------------------------------
const yyNumRules = 74
const yyEndOfBuffer = 75
var yyAccept = [242]int16{   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       75,   73,   72,   72,   48,   69,   73,   45,   73,   70,
       51,   51,    3,   73,    4,   73,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   37,   38,   61,   62,   55,   74,   67,   68,
       64,   74,   74,   42,   42,   48,    8,   46,   44,   45,
        2,   40,   43,    0,   51,    0,    0,    0,    0,    9,
        5,    7,    6,   10,   47,   50,   50,   50,   50,   25,
       50,   50,   50,   50,   50,   50,   50,   50,   26,   50,
       50,   50,   27,   24,   50,   50,   50,   50,   50,   50,

       50,    0,    0,   61,   63,   58,   59,   57,   56,   63,
       67,   64,   64,   66,   65,   41,   43,   52,   51,   54,
       53,   30,   23,   31,   50,   50,   50,   50,   50,   29,
       50,   50,   50,   50,   50,   50,   50,   50,   22,   50,
       50,   50,   50,   50,   50,   50,   71,    0,    0,    0,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   49,   50,   14,   50,   50,   13,   50,   28,
       20,   17,    0,    0,    0,    0,    0,   71,   60,   16,
       50,   50,   50,   21,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,    0,    0,   50,   50,   50,   50,

       50,   12,   36,   50,   49,   50,   19,   50,   50,    0,
        0,    0,    0,    0,   71,   50,   50,   50,   50,   50,
       39,   34,   11,   15,    0,   71,    0,    0,    0,   50,
       35,   50,   33,   18,    0,    0,    0,    1,   50,   32,
        0,
    }

var yyEc = [256]byte{    0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    1,    1,    8,
        8,    9,    1,    1,    8,   10,   11,   12,   13,   14,
       15,   16,   16,   17,   16,   18,   19,    1,    1,   20,
       21,   22,    8,   23,   24,   25,   24,   24,   24,   24,
       26,   26,   26,   26,   27,   26,   28,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
        8,   29,    8,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   26,   26,   40,   41,   42,
       43,   44,   26,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,    8,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,
    }

var yyMeta = [56]byte{    0,
        1,    2,    3,    1,    4,    1,    1,    2,    5,    6,
        7,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        9,    1,    1,   10,   10,   11,   12,   12,   13,   11,
       10,   10,   10,   10,   10,   10,   11,   11,   11,   11,
       11,   11,   12,   11,   11,   11,   11,   11,   11,   11,
       12,   11,   11,    1,    1,
    }

var yyBase = [264]uint16{   0,
        0,    0,   53,   54,   57,   58,    0,    0,  349,  348,
      356,  646,  646,  646,  334,  646,    0,  343,  341,   53,
       53,   57,   45,  329,   49,    0,    0,   32,  306,  297,
       58,  296,   34,   42,  292,   54,  289,  285,  282,   50,
      289,  288,  315,  646,    0,  646,  646,   86,    0,  646,
       59,  314,  646,  646,  313,  302,  646,    0,  646,  313,
      646,  646,    0,  104,    0,  296,  295,   97,    0,  646,
      646,  646,  646,  646,    0,    0,  279,   73,  285,    0,
      275,  269,  275,  274,  268,  272,  262,  260,   91,  256,
      255,   93,    0,    0,  262,  258,  252,  261,  247,  243,

      248,   81,  118,    0,  646,  646,  646,  646,  646,    0,
        0,  235,  646,  646,  646,  646,    0,  129,  646,  137,
        0,    0,    0,    0,  241,  121,  234,  229,  239,    0,
      233,  240,  228,  230,  117,  236,  237,  236,    0,  217,
      230,  225,  222,  227,  214,  225,  646,  250,  167,    0,
      219,  212,  219,  197,  213,  201,  194,  212,  197,  193,
      214,  216,  196,  189,    0,  180,  194,    0,  179,    0,
        0,    0,  211,  208,  221,    0,  147,    0,  646,    0,
      171,  178,  172,    0,  176,  171,  173,  165,  177,  175,
      174,  173,  160,  169,  275,  148,  166,  162,  154,  143,

      150,    0,    0,  159,    0,  147,    0,  155,  143,  329,
        0,  383,  177,  151,    0,  144,  131,  137,  104,  100,
        0,    0,    0,    0,  152,  122,  155,   92,  156,   60,
        0,   52,    0,    0,  162,    0,  163,    0,   46,    0,
      646,  438,  451,  464,  477,  483,  488,  496,  503,  508,
      513,  524,  534,  546,  559,  571,  584,  590,  593,  603,
      616,  622,  632,
    }

var yyDef = [264]int16{   0,
      241,    1,  242,  242,  243,  243,  244,  244,  245,  245,
      241,  241,  241,  241,  246,  241,  247,  248,  241,  241,
      249,  249,  241,  241,  241,  250,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  252,  241,  253,  241,  241,  254,  255,  241,
      241,  256,  241,  241,  241,  246,  241,  247,  241,  248,
      241,  241,  257,  241,   22,  241,  241,  241,  258,  241,
      241,  241,  241,  241,  250,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,

      251,  252,  241,  253,  241,  241,  241,  241,  241,  259,
      255,  241,  241,  241,  241,  241,  257,  241,  241,  241,
      258,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  241,  260,  261,  262,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  260,  241,  261,  175,  175,  175,  241,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  263,  175,  251,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  263,
      210,  260,  175,  210,  210,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  260,  260,  175,  210,  210,  251,
      251,  251,  251,  251,  260,  210,  210,  251,  251,  251,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,
    }

var yyNxt = [702]uint16{   0,
       12,   13,   14,   15,   16,   17,   18,   12,   12,   19,
       20,   21,   22,   22,   22,   22,   22,   22,   22,   23,
       24,   25,   26,   27,   27,   27,   27,   27,   12,   27,
       28,   27,   29,   27,   30,   31,   32,   27,   33,   27,
       34,   35,   36,   37,   38,   39,   40,   41,   27,   42,
       27,   27,   27,   43,   44,   46,   46,   47,   47,   50,
       50,   62,   64,   63,   70,   71,   64,   51,   51,   73,
       74,   77,   90,   78,   88,   89,   91,   79,   80,   66,
       67,   48,   48,   66,   67,   52,   52,   98,   83,   93,
      106,  103,  240,  239,   99,   68,   84,  112,   94,  241,

       85,  238,  237,   69,  113,   86,  123,  241,  120,  120,
      120,  120,  120,  120,  107,  118,  118,  118,  118,  118,
      118,  118,  118,  134,  124,  138,  148,  108,  149,  161,
      174,  162,  109,  234,  163,  147,  110,  135,  233,  139,
      118,  118,  118,  118,  118,  118,  118,  118,  120,  120,
      120,  120,  120,  120,  152,  195,  195,  196,  196,  228,
      235,  229,  236,  195,  228,  196,  229,  153,  176,  102,
      174,  228,  212,  229,  176,  232,  231,  177,  176,  176,
      176,  176,  176,  176,  176,  176,  230,  227,  224,  223,
      176,  176,  222,  221,  220,  219,  218,  176,  176,  176,

      176,  176,  176,  217,  216,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  102,  174,
      194,  178,  176,  102,  193,  192,  191,  190,  176,  163,
      163,  177,  176,  176,  176,  176,  176,  176,  176,  176,
      189,  188,  187,  186,  176,  176,  185,  184,  183,  182,
      181,  176,  176,  176,  176,  176,  176,  180,  174,  172,
      135,  171,  170,  169,  168,  167,  166,  165,  164,  160,
      159,  158,  157,  156,  155,  178,  211,  212,  154,  151,
      113,  146,  211,  213,  145,  214,  211,  211,  211,  211,
      211,  211,  211,  211,  144,  143,  142,  141,  211,  211,

      140,  137,  136,  133,  132,  211,  211,  211,  211,  211,
      211,  131,  130,  129,  128,  127,  126,  125,  122,  119,
      119,   59,  241,  116,  115,  103,  101,  100,   97,  215,
      211,  212,   96,   95,   92,   87,  211,  213,   82,  214,
      211,  211,  211,  211,  211,  211,  211,  211,   81,   72,
       61,   59,  211,  211,   57,  241,   55,   55,  241,  211,
      211,  211,  211,  211,  211,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  215,  212,  212,  241,  241,  241,  241,
      212,  174,  241,  225,  212,  212,  212,  212,  212,  212,

      212,  212,  241,  241,  241,  241,  212,  212,  241,  241,
      241,  241,  241,  212,  212,  212,  212,  212,  212,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  226,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       56,   56,   56,   56,   56,   58,  241,   58,   58,   58,

       60,  241,  241,   60,  241,   60,   60,   60,   65,  241,
       65,  241,  241,  241,   65,   75,  241,   75,   75,   75,
       76,  241,   76,   76,   76,  102,  102,  241,  241,  241,
      102,  102,  241,  102,  104,  104,  241,  241,  104,  104,
      104,  104,  104,  104,  104,  104,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  111,
      111,  241,  111,  111,  111,  241,  111,  111,  111,  111,
      111,  114,  114,  241,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  117,  117,  241,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  121,  241,  121,

      150,  241,  150,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  173,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  179,
      241,  179,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  210,   11,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,
    }

var yyChk = [702]int16{   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    5,
        6,   20,   21,   20,   23,   23,   22,    5,    6,   25,
       25,   28,   34,   28,   33,   33,   34,   28,   28,   21,
       21,    3,    4,   22,   22,    5,    6,   40,   31,   36,
       48,  102,  239,  232,   40,   21,   31,   51,   36,   22,

       31,  230,  228,   21,   51,   31,   78,   22,   68,   68,
       68,   68,   68,   68,   48,   64,   64,   64,   64,   64,
       64,   64,   64,   89,   78,   92,  103,   48,  103,  135,
      226,  135,   48,  220,  135,  102,   48,   89,  219,   92,
      118,  118,  118,  118,  118,  118,  118,  118,  120,  120,
      120,  120,  120,  120,  126,  177,  196,  177,  196,  214,
      225,  214,  225,  227,  229,  227,  229,  126,  149,  149,
      235,  237,  235,  237,  149,  218,  217,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  216,  213,  209,  208,
      149,  149,  206,  204,  201,  200,  199,  149,  149,  149,

      149,  149,  149,  198,  197,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  183,  182,  181,  174,  173,
      169,  149,  175,  175,  167,  166,  164,  163,  175,  162,
      161,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      160,  159,  158,  157,  175,  175,  156,  155,  154,  153,
      152,  175,  175,  175,  175,  175,  175,  151,  148,  146,
      145,  144,  143,  142,  141,  140,  138,  137,  136,  134,
      133,  132,  131,  129,  128,  175,  195,  195,  127,  125,
      112,  101,  195,  195,  100,  195,  195,  195,  195,  195,
      195,  195,  195,  195,   99,   98,   97,   96,  195,  195,

       95,   91,   90,   88,   87,  195,  195,  195,  195,  195,
      195,   86,   85,   84,   83,   82,   81,   79,   77,   67,
       66,   60,   56,   55,   52,   43,   42,   41,   39,  195,
      210,  210,   38,   37,   35,   32,  210,  210,   30,  210,
      210,  210,  210,  210,  210,  210,  210,  210,   29,   24,
       19,   18,  210,  210,   15,   11,   10,    9,    0,  210,
      210,  210,  210,  210,  210,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  210,  212,  212,    0,    0,    0,    0,
      212,  212,    0,  212,  212,  212,  212,  212,  212,  212,

      212,  212,    0,    0,    0,    0,  212,  212,    0,    0,
        0,    0,    0,  212,  212,  212,  212,  212,  212,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  212,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      246,  246,  246,  246,  246,  247,    0,  247,  247,  247,

      248,    0,    0,  248,    0,  248,  248,  248,  249,    0,
      249,    0,    0,    0,  249,  250,    0,  250,  250,  250,
      251,    0,  251,  251,  251,  252,  252,    0,    0,    0,
      252,  252,    0,  252,  253,  253,    0,    0,  253,  253,
      253,  253,  253,  253,  253,  253,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  255,
      255,    0,  255,  255,  255,    0,  255,  255,  255,  255,
      255,  256,  256,    0,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  257,  257,    0,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  258,    0,  258,

      259,    0,  259,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  262,
        0,  262,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,
    }

/* Table of booleans, true if rule could match eol. */
var yyRuleCanMatchEol = [75]int32{   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,     };

//line grammar/lexer.l:1
/*
Copyright (c) 2007-2013. The YARA Authors. All Rights Reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* Lexical analyzer for YARA */

//line grammar/lexer.l:71

 

// Define a constant for end-of-file
const eof = 0

// These globals must be accessible to the goyacc parser.
// Bear in mind that the xx prefix is used because the parser is generated
// with this prefix in order to avoid name collisions.
var yylval *xxSymType
var err error // Actually, this is global for lexer action access.





//line grammar/lexer.go:491
// SKEL ----------------------------------------------------------------

const yyInitial  = 0
const str = 1
const regexp = 2
const include = 3
const comment = 4

const yyReadBufSize = 16384

func (yy *Scanner) input(offset, maxRead int) int {

// [5.0] fread()/read() definition of yy_INPUT goes here ---------------
// nothing here, all moved to skeleton
// SKEL ----------------------------------------------------------------

	if yy.Interactive {
		b := make([]byte, 1)
		var n int
		for n = 0; n < maxRead; n++ {
			nn, err := yy.inputFile.Read(b)
			if err != nil && err != io.EOF {
				log.Panicln("Reading 1 byte:", err)
			}
			if nn < 1 {
				break
			}
			yy.chBuf[offset+n] = b[0]
			if b[0] == '\n' {
				n++
				break
			}
		}
		return n
	}

	n, err := yy.inputFile.Read(yy.chBuf[offset:offset+maxRead])
	if err != nil  && err != io.EOF {
		log.Panicf("Reading %d bytes: %v\n", maxRead, err)
	}
	return n
}

/* [6.0] YY_RULE_SETUP definition goes here --------------------------*/

// SKEL ----------------------------------------------------------------

// The main scanner function which does all the work.
func (yy *Scanner) Lex() YYtype {
	var yyCurrentState int
	var yyBp, yyCp int
	var yyAct int
	var yytext []byte
	var yyleng int
	var yylineno int
	_ = yytext
	_ = yyleng
	_ =  yylineno 

	if !yy.init {
		yy.init = true
		
		if yy.In == nil {
			yy.In = os.Stdin
		}
		if yy.Out == nil {
			yy.Out = os.Stdout
		}
		yy.initBuffer(yy.In)
		yy.loadBufferState()
	}

	yyout := yy.Out
	_ = yyout

// [7.0] user's declarations go here -----------------------------------
//line grammar/lexer.l:110


//line grammar/lexer.go:571
// SKEL ----------------------------------------------------------------

	for { // loops until end-of-file is reached

// [8.0] yy''more-related code goes here -------------------------------
// SKEL ----------------------------------------------------------------

		yyCp = yy.cBufP

		/* Support of yytext. */
		yy.chBuf[yyCp] = yy.holdChar

		// yyBp points to the position in yy_ch_buf of the start of
		// the current run.
		yyBp = yyCp

// [9.0] code to set up and find next match goes here ------------------
		yyCurrentState = yy.start
yyMatch:
		for {
			yyC := int(yyEc[yy.chBuf[yyCp]])
						if yyAccept[yyCurrentState] != 0 {
				yy.lastAcceptingState = yyCurrentState
				yy.lastAcceptingCpos = yyCp
			}
			for int(yyChk[int(yyBase[yyCurrentState])+yyC]) != yyCurrentState {
				yyCurrentState = int(yyDef[yyCurrentState])
				if yyCurrentState >= 242 {
					yyC = int(yyMeta[yyC])
				}
			}
			yyCurrentState = int(yyNxt[int(yyBase[yyCurrentState])+yyC])
			yyCp++
			if yyCurrentState == 241 {
				break
			}
		}
		yyCp = yy.lastAcceptingCpos
		yyCurrentState = yy.lastAcceptingState
// SKEL ----------------------------------------------------------------

	yyFindAction:

// [10.0] code to find the action number goes here ---------------------
		yyAct = int(yyAccept[yyCurrentState])
// SKEL ----------------------------------------------------------------

		yy.textPtr = yyBp

// [2.0] code to fiddle yytext and yyleng for yy''more() goes here -------
	yyleng = yyCp - yyBp
// SKEL ----------------------------------------------------------------

		yy.holdChar = yy.chBuf[yyCp]
		yy.chBuf[yyCp] = 0

// [3.0] code to copy yytext_ptr to yytext[] goes here, if %array ------
// SKEL ----------------------------------------------------------------

		yy.cBufP = yyCp
		yytext = yy.chBuf[yy.textPtr:yyCp]
 
// [11.0] code for yylineno update goes here ---------------------------

		if yyAct != yyEndOfBuffer && yyRuleCanMatchEol[yyAct] != 0 {
			for yyl := 0; yyl < yyleng; yyl++ {
				if yytext[yyl] == '\n' {
					yy.Lineno++
				}
			}
		}

// SKEL ----------------------------------------------------------------

	doAction: // This label is used only to access EOF actions.

// [12.0] debug code goes here -----------------------------------------
// SKEL ----------------------------------------------------------------

		switch yyAct { // beginning of action switch

// [13.0] actions go here ----------------------------------------------
			case 0: // must back up
			// undo the effects of yy_DO_BEFORE_ACTION
			yy.chBuf[yyCp] = yy.holdChar
			yyCp = yy.lastAcceptingCpos
			yyCurrentState = yy.lastAcceptingState
			goto yyFindAction

case 1:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }

//line grammar/lexer.l:112
{ return _CONDITION_;   }
case 2:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:113
{ return _DOT_DOT_;     }
case 3:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:114
{ return _LT_;          }
case 4:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:115
{ return _GT_;          }
case 5:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:116
{ return _LE_;          }
case 6:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:117
{ return _GE_;          }
case 7:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:118
{ return _EQ_;          }
case 8:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:119
{ return _NEQ_;         }
case 9:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:120
{ return _SHIFT_LEFT_;  }
case 10:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:121
{ return _SHIFT_RIGHT_; }
case 11:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:122
{ return _PRIVATE_;     }
case 12:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:123
{ return _GLOBAL_;      }
case 13:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:124
{ return _RULE_;        }
case 14:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:125
{ return _META_;        }
case 15:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:126
{ return _STRINGS_;     }
case 16:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:127
{ return _ASCII_;       }
case 17:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:128
{ return _WIDE_;        }
case 18:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:129
{ return _FULLWORD_;    }
case 19:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:130
{ return _NOCASE_;      }
case 20:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:131
{ return _TRUE_;        }
case 21:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:132
{ return _FALSE_;       }
case 22:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:133
{ return _NOT_;         }
case 23:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:134
{ return _AND_;         }
case 24:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:135
{ return _OR_;          }
case 25:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:136
{ return _AT_;          }
case 26:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:137
{ return _IN_;          }
case 27:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:138
{ return _OF_;          }
case 28:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:139
{ return _THEM_;        }
case 29:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:140
{ return _FOR_;         }
case 30:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:141
{ return _ALL_;         }
case 31:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:142
{ return _ANY_;         }
case 32:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:143
{ return _ENTRYPOINT_;  }
case 33:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:144
{ return _FILESIZE_;    }
case 34:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:145
{ return _MATCHES_;     }
case 35:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:146
{ return _CONTAINS_;    }
case 36:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:147
{ return _IMPORT_;      }
case 37:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:149
{ return _LBRACE_; }
case 38:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:150
{ 
                          if collect {
                            collect = false
                          }
                          return _RBRACE_;
                        }
case 39:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:156
{ return _INCLUDE_; }
case 40:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:158
{ yy.start = 1 + 2*  (comment);       }
case 41:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:159
{ yy.start = 1 + 2*  (yyInitial );       }
case 42:
/* rule 42 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:160
{ /* skip comments */   }
case 43:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:163
{ /* skip single-line comments */ }
case (yyEndOfBuffer + yyInitial  + 1) :
	fallthrough
case (yyEndOfBuffer + str + 1) :
	fallthrough
case (yyEndOfBuffer + regexp + 1) :
	fallthrough
case (yyEndOfBuffer + include + 1) :
	fallthrough
case (yyEndOfBuffer + comment + 1) :
//line grammar/lexer.l:165
{ return eof }
case 44:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:168
{
  yylval.s = string(yytext)
  return _STRING_IDENTIFIER_WITH_WILDCARD_;
}
case 45:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:174
{
  yylval.s = string(yytext)
  return _STRING_IDENTIFIER_;
}
case 46:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:180
{
  yylval.strcnt = data.StringCount{Identifier: YYtext[1:]}
  return _STRING_COUNT_;
}
case 47:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:186
{
  yylval.stroff = data.StringOffset{Base: YYtext[1:]}
  return _STRING_OFFSET_;
}
case 48:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:192
{
  yylval.strlen = data.StringLength{Base: YYtext[1:]}
  return _STRING_LENGTH_;
}
case 49:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:198
{
  yylval.s = YYtext
  return _INTEGER_FUNCTION_;
}
case 50:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:204
{
  yylval.s = string(yytext)
  return _IDENTIFIER_;
}
case 51:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:210
{
  var err error
  s := strings.TrimRight(YYtext, "MKB")
  yylval.i64, err = strconv.ParseInt(s, 10, 64)
  if err != nil {
      panic(fmt.Errorf("Number conversion error: %s", err))
  }

  if strings.HasSuffix(YYtext, "KB") {
      if yylval.i64 > math.MaxInt64 / 1024 {
          err := fmt.Errorf("Integer overflow: %s; max %d",
              YYtext, math.MaxInt64)
          panic(err)
      } else {
          yylval.i64 *= 1024
      }
  } else if strings.HasSuffix(YYtext, "MB") {
      if yylval.i64 > math.MaxInt64 / 1048576 {
          err := fmt.Errorf("Integer overflow: %s; max %d",
              YYtext, math.MaxInt64)
          panic(err)
      } else {
          yylval.i64 *= 1048576
      }
  }
  return _NUMBER_;
}
case 52:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:238
{
  result, err := strconv.ParseFloat(YYtext, 64)
  if err != nil {
    panic(err)
  }
  yylval.f64 = result
  return _DOUBLE_;
}
case 53:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:247
{
  var err error
  yylval.i64, err = strconv.ParseInt(YYtext, 0, 64)
  if err != nil {
      panic(fmt.Errorf("Number conversion error: %s", err))
  }

  return _NUMBER_;
}
case 54:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:257
{
  var err error
  s := strings.TrimLeft(YYtext, "0o")
  yylval.i64, err = strconv.ParseInt(s, 8, 64)
  if err != nil {
      panic(fmt.Errorf("Number conversion error: %s", err))
  }
  return _NUMBER_;
}
case 55:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:268
{     /* saw closing quote - all done */

  // NOTE: textBuilder.String() will end with `"` char
  collectText = false
  yylval.s = strings.TrimSuffix(textBuilder.String(), `"`)

  yy.start = 1 + 2*  (yyInitial );

  return _TEXT_STRING_;
}
case 56:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:280
{
}
case 57:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:284
{
}
case 58:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:288
{
}
case 59:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:292
{
}
case 60:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:296
{
}
case 61:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:300
{ }
case 62:
/* rule 62 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:303
{
  panic(fmt.Errorf("unterminated string"))
}
case 63:
/* rule 63 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:308
{
  panic(fmt.Errorf("illegal escape sequence"))
}
case 64:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:313
{
  collectText = false

  txt := strings.TrimSuffix(textBuilder.String(), YYtext)
  
  var mods data.StringModifiers

  for _, c := range YYtext {
      switch c {
      case 'i':
          mods.I = true
      
      case 's':
          mods.S = true
      
      case '/':
          // Ignore
      
      default:
          // Should be impossible
          panic(fmt.Errorf("Invalid regex modifier: %c", c))
      }
  }

  yylval.reg = regexPair {
      txt,
      mods,
  }

  yy.start = 1 + 2*  (yyInitial );
  return _REGEXP_;
}
case 65:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:347
{
}
case 66:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:351
{
}
case 67:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:355
{ }
case 68:
/* rule 68 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:358
{
  panic(fmt.Errorf("unterminated regular expression"))
}
case 69:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:363
{
  collectText = true
  textBuilder.Reset()
  yy.start = 1 + 2*  (str);
}
case 70:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:370
{
  collectText = true
  textBuilder.Reset()
  yy.start = 1 + 2*  (regexp);
}
case 71:
/* rule 71 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:377
{
  // Match hex-digits with whitespace or comments. The latter are stripped
  // out by hex_lexer.l

  // NOTE: The above comment may not apply. We plan to not use hex_lexer.l

  // No need to collect like str and regexp start conditions
  yylval.s = strings.Trim(YYtext, "{}")

  return _HEX_STRING_;
}
case 72:
/* rule 72 can match eol */

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:390
/* skip whitespace */
case 73:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:392
{

  r := int(yytext[0])

  if r >= 32 && r < 127 {
    return r
  }

  panic(fmt.Errorf("non-ascii byte '%d'", r))
}
case 74:

	yylineno = yy.Lineno
	YYtext = string(yytext)

  if collectText {
    textBuilder.Write(yytext)
  }


//line grammar/lexer.l:403
yyout.Write(yytext) 
//line grammar/lexer.go:1720
// SKEL ----------------------------------------------------------------

		case yyEndOfBuffer:
			/* Amount of text matched not including the EOB char. */
			yyAmountOfMatchedText := yyCp - yy.textPtr - 1

			/* Undo the effects of yy_DO_BEFORE_ACTION. */
			yy.chBuf[yyCp] = yy.holdChar
			 
			if yy.bufferStatus == yyBufferNew {
				/* We're scanning a new file or input source.  It's
				 * possible that this happened because the user
				 * just pointed yyin at a new source and called
				 * yylex().  If so, then we have to assure
				 * consistency between yy_CURRENT_BUFFER and our
				 * globals.  Here is the right place to do so, because
				 * this is the first action (other than possibly a
				 * back-up) that will match for the new input source.
				 */
				yy.nChars = yy.bufNChars
				yy.inputFile = yy.In
				yy.bufferStatus = yyBufferNormal
			}

			/* Note that here we test for yy_c_buf_p "<=" to the position
			 * of the first EOB in the buffer, since yy_c_buf_p will
			 * already have been incremented past the NUL character
			 * (since all states make transitions on EOB to the
			 * end-of-buffer state).  Contrast this with the test
			 * in input().
			 */
			if yy.cBufP <= yy.nChars {
				/* This was really a NUL. */
				var yyNextState int

				yy.cBufP = yy.textPtr + yyAmountOfMatchedText

				yyCurrentState = yy.getPreviousState()

				/* Okay, we're now positioned to make the NUL
				 * transition.  We couldn't have
				 * yy_get_previous_state() go ahead and do it
				 * for us because it doesn't know how to deal
				 * with the possibility of jamming (and we don't
				 * want to build jamming into it because then it
				 * will run more slowly).
				 */

				yyNextState = yy.tryNulTrans(yyCurrentState)

				yyBp = yy.textPtr + 0 

				if yyNextState != 0 {
					/* Consume the NUL. */
					yy.cBufP++
					yyCp = yy.cBufP
					yyCurrentState = yyNextState
					goto yyMatch
				} else {

// [14.0] code to do back-up for compressed tables and set up yy_cp goes here
				yyCp = yy.lastAcceptingCpos
				yyCurrentState = yy.lastAcceptingState
// SKEL ----------------------------------------------------------------

					goto yyFindAction
				}

			} else {

				switch yy.getNextBuffer() {
				case eobActEndOfFile:
					yy.didBufferSwitchOnEof = false

					if yy.Wrap(yy) {
						// Note: because we've taken care in
						// yy_get_next_buffer() to have set up
						// yytext, we can now set up
						// yy.cBufP so that if some total
						// hoser (like flex itself) wants to
						// call the scanner after we return the
						// yy_NULL, it'll still work - another
						// yy_NULL will get returned.
						yy.cBufP = yy.textPtr + 0 

						yyAct = (yyEndOfBuffer + ((yy.start - 1) / 2)  + 1) 
						goto doAction
					} else {
						if !yy.didBufferSwitchOnEof {
							yy.NewFile()
						}
					}
				case eobActContinueScan:
					yy.cBufP = yy.textPtr + yyAmountOfMatchedText

					yyCurrentState = yy.getPreviousState()

					yyCp = yy.cBufP
					yyBp = yy.textPtr + 0 
					goto yyMatch
				case eobActLastMatch:
					yy.cBufP = yy.nChars

					yyCurrentState = yy.getPreviousState()

					yyCp = yy.cBufP
					yyBp = yy.textPtr + 0 
					goto yyFindAction
				}
			}

		default:
			log.Panicln("fatal flex scanner internal error--no action found:", yyAct)
		} // end of action switch
	} // end of scanning one token
	var yyvalue YYtype
	return yyvalue
} // end of yylex

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
func (yy *Scanner) getNextBuffer() int {

	var numberToMove int
	var retval int

	if yy.cBufP > yy.nChars+1 {
		log.Panic("fatal flex scanner internal error--end of buffer missed")
	}

	if !yy.fillBuffer {
		// Don't try to fill the buffer, so this is an EOF.
		if yy.cBufP-yy.textPtr-0  == 1 {
			// We matched a single character, the EOB, so
			// treat this as a final EOF.
			return eobActEndOfFile
		} else {
			// We matched some text prior to the EOB, first
			// process it.
			return eobActLastMatch
		}
	}

	// Try to read more data.

	// First move last chars to start of buffer.
	numberToMove = yy.cBufP - yy.textPtr - 1

	copy(yy.chBuf, yy.chBuf[yy.textPtr:yy.textPtr+numberToMove])

	if yy.bufferStatus == yyBufferEofPending {
		// don't do the read, it's not guaranteed to return an EOF,
		// just force an EOF
		yy.nChars = 0
		yy.bufNChars = 0
	} else {
		numToRead := yy.bufSize - numberToMove - 1

		for numToRead <= 0 {
			// Not enough room in the buffer - grow it.

			yyCBufPOffset := yy.cBufP

			new_size := yy.bufSize * 2

			if new_size <= 0 {
				yy.bufSize += yy.bufSize / 8
			} else {
				yy.bufSize *= 2
			}

			// Include room in for 2 EOB chars.
			bb := make([]byte, yy.bufSize+2-len(yy.chBuf))
			yy.chBuf = append(yy.chBuf, bb...)

			yy.cBufP = yyCBufPOffset

			numToRead = yy.bufSize - numberToMove - 1

		}

		if numToRead > yyReadBufSize {
			numToRead = yyReadBufSize
		}

		// Read in more data.
		yy.nChars = yy.input(numberToMove, numToRead)
		yy.bufNChars = yy.nChars
	}

	if yy.nChars == 0 {
		if numberToMove == 0  {
			retval = eobActEndOfFile
			yy.Restart(yy.In)
		} else {
			retval = eobActLastMatch
			yy.bufferStatus = yyBufferEofPending
		}
	} else {
		retval = eobActContinueScan
	}

	if yy.nChars+numberToMove > yy.bufSize {
		// Extend the array by 50%, plus the number we really need. *
		newSize := yy.nChars + numberToMove + (yy.nChars >> 1)
		if leng := len(yy.chBuf); leng < newSize {
			chBuf := make([]byte, newSize-leng)
			yy.chBuf = append(yy.chBuf, chBuf...)
		}
	}

	yy.nChars += numberToMove
	//yy.bufNChars += numberToMove // TODO: missing in C skel, bug?
	yy.chBuf[yy.nChars] = yyEndOfBufferChar
	yy.chBuf[yy.nChars+1] = yyEndOfBufferChar

	yy.textPtr = 0

	return retval
}

/* yy_get_previous_state - get the state just before the EOB char was reached */
func (yy *Scanner) getPreviousState() int {

	var yyCurrentState int
	var yyCp int

// [15.0] code to get the start state into yy_current_state goes here --
	yyCurrentState = yy.start
// SKEL ----------------------------------------------------------------

	for yyCp = yy.textPtr + 0 ; yyCp < yy.cBufP; yyCp++ {

// [16.0] code to find the next state goes here ------------------------
		yyC := yyIfElse(yy.chBuf[yyCp] != 0, int(yyEc[yy.chBuf[yyCp]]), 1)
				if yyAccept[yyCurrentState] != 0 {
			yy.lastAcceptingState = yyCurrentState
			yy.lastAcceptingCpos = yyCp
		}
		for int(yyChk[int(yyBase[yyCurrentState])+yyC]) != yyCurrentState {
			yyCurrentState = int(yyDef[yyCurrentState])
			if yyCurrentState >= 242 {
				yyC = int(yyMeta[yyC])
			}
		}
		yyCurrentState = int(yyNxt[int(yyBase[yyCurrentState])+yyC])
// SKEL ----------------------------------------------------------------

	}
	return yyCurrentState
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *      next_state = yy_try_NUL_trans( current_state );
 */
func (yy *Scanner) tryNulTrans(yyCurrentState int) int {

	var yyIsJam bool
	var yyCp int
	_ = yyCp

// [17.0] code to find the next state, and perhaps do backing up, goes here
	yyCp = yy.cBufP

	yyC := 1
		if yyAccept[yyCurrentState] != 0 {
		yy.lastAcceptingState = yyCurrentState
		yy.lastAcceptingCpos = yyCp
	}
	for int(yyChk[int(yyBase[yyCurrentState])+yyC]) != yyCurrentState {
		yyCurrentState = int(yyDef[yyCurrentState])
		if yyCurrentState >= 242 {
			yyC = int(yyMeta[yyC])
		}
	}
	yyCurrentState = int(yyNxt[int(yyBase[yyCurrentState])+yyC])
	if yyCurrentState == 241 {
		yyIsJam = true
	}
// SKEL ----------------------------------------------------------------

	if yyIsJam {
		return 0
	}
	return yyCurrentState
}

func (yy *Scanner) Input() (byte, error) {

	yy.chBuf[yy.cBufP] = yy.holdChar

	if yy.chBuf[yy.cBufP] == yyEndOfBufferChar {
		// yy_c_buf_p now points to the character we want to return.
		// If this occurs *before* the EOB characters, then it's a
		// valid NUL; if not, then we've hit the end of the buffer.
		if yy.cBufP < yy.nChars {
			// This was really a NUL.
			yy.chBuf[yy.cBufP] = 0
		} else {
			// need more input
			offset := yy.cBufP - yy.textPtr
			yy.cBufP++

			switch yy.getNextBuffer() {
			case eobActLastMatch:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
				yy.Restart(yy.In)

				fallthrough

			case eobActEndOfFile:
				if yy.Wrap(yy) {
					return 0, io.EOF
				}

				if !yy.didBufferSwitchOnEof {
					yy.Restart(yy.In)
				}

				return yy.Input()

			case eobActContinueScan:
				yy.cBufP = yy.textPtr + offset
			}
		}
	}

	c := yy.chBuf[yy.cBufP]
	yy.chBuf[yy.cBufP] = 0	// preserve yytext
	yy.cBufP++
	yy.holdChar = yy.chBuf[yy.cBufP]

// [19.0] update BOL and yylineno --------------------------------------
	if c == '\n' {
		yy.Lineno++
	}
// SKEL ----------------------------------------------------------------

return c, nil
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c yyInitial  .
 */
func (yy *Scanner) Restart(input_file io.Reader) {
	yy.initBuffer(input_file)
	yy.loadBufferState()
}

func (yy *Scanner) loadBufferState() {
	yy.nChars = yy.bufNChars
	yy.cBufP = yy.bufPos
	yy.textPtr = yy.cBufP
	yy.In = yy.inputFile
	yy.holdChar = yy.chBuf[yy.cBufP]
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
func (yy *Scanner) initBuffer(file io.Reader) {

	yy.flushBuffer()

	yy.inputFile = file

	yy.fillBuffer = true

	yy.Interactive = yy.IsInteractive(file)

}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
func (yy *Scanner) flushBuffer() {

	yy.bufNChars = 0

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	yy.chBuf[0] = yyEndOfBufferChar
	yy.chBuf[1] = yyEndOfBufferChar

	yy.bufPos = 0

	yy.atBol = 1
	yy.bufferStatus = yyBufferNew

	yy.loadBufferState()
}

func yyIfElse(b bool, i1, i2 int) int {
	if b {
		return i1
	}
	return i2
}

func YYmain(filenames ...string) (interface{}, error) {

	var errval error

	yy := NewScanner()

	yy.Filename = "<stdin>"

	if len(filenames) > 0 {
		yy.Filename = filenames[0]
		yy.In, errval = os.Open(yy.Filename)
		if errval != nil {
			return nil, errval
		}
		yy.Wrap = func(yyy *Scanner) bool {
			if len(filenames) == 0 {
				// should not happen
				return true
			}
			yyy.In.(*os.File).Close()
			filenames = filenames[1:]
			if len(filenames) == 0 {
				return true
			}
			yyy.Filename = filenames[0]
			yyy.In, errval = os.Open(yyy.Filename)
			if errval != nil {
				return true
			}
			return false
		}
	}

	return yy.Lex(), errval

}

// END OF SKELL --------------------------------------------------------
//line grammar/lexer.l:403



