// Code generated by goyacc -p xx -o /grammar/parser.go /grammar/grammar.y. DO NOT EDIT.

//line /grammar/grammar.y:31
package grammar

import __yyfmt__ "fmt"

//line /grammar/grammar.y:31
import (
	"fmt"
	"strings"

	"github.com/Northern-Lights/yara-parser/data"
)

var ParsedRuleset data.RuleSet

type regexPair struct {
	text string
	mods data.StringModifiers
}

//line /grammar/grammar.y:128
type xxSymType struct {
	yys int
	i64 int64
	s   string
	ss  []string

	rm  data.RuleModifiers
	m   data.Metas
	mp  data.Meta
	mps data.Metas
	mod data.StringModifiers
	reg regexPair
	ys  data.String
	yss data.Strings
	yr  data.Rule
}

const _END_OF_FILE_ = 0
const _END_OF_INCLUDED_FILE_ = 57347
const _DOT_DOT_ = 57348
const _RULE_ = 57349
const _PRIVATE_ = 57350
const _GLOBAL_ = 57351
const _META_ = 57352
const _STRINGS_ = 57353
const _CONDITION_ = 57354
const _IDENTIFIER_ = 57355
const _STRING_IDENTIFIER_ = 57356
const _STRING_COUNT_ = 57357
const _STRING_OFFSET_ = 57358
const _STRING_LENGTH_ = 57359
const _STRING_IDENTIFIER_WITH_WILDCARD_ = 57360
const _NUMBER_ = 57361
const _DOUBLE_ = 57362
const _INTEGER_FUNCTION_ = 57363
const _TEXT_STRING_ = 57364
const _HEX_STRING_ = 57365
const _REGEXP_ = 57366
const _ASCII_ = 57367
const _WIDE_ = 57368
const _XOR_ = 57369
const _NOCASE_ = 57370
const _FULLWORD_ = 57371
const _AT_ = 57372
const _FILESIZE_ = 57373
const _ENTRYPOINT_ = 57374
const _ALL_ = 57375
const _ANY_ = 57376
const _IN_ = 57377
const _OF_ = 57378
const _FOR_ = 57379
const _THEM_ = 57380
const _MATCHES_ = 57381
const _CONTAINS_ = 57382
const _IMPORT_ = 57383
const _TRUE_ = 57384
const _FALSE_ = 57385
const _LBRACE_ = 57386
const _RBRACE_ = 57387
const _INCLUDE_ = 57388
const _OR_ = 57389
const _AND_ = 57390
const _EQ_ = 57391
const _NEQ_ = 57392
const _LT_ = 57393
const _LE_ = 57394
const _GT_ = 57395
const _GE_ = 57396
const _SHIFT_LEFT_ = 57397
const _SHIFT_RIGHT_ = 57398
const _NOT_ = 57399
const UNARY_MINUS = 57400

var xxToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"_END_OF_FILE_",
	"_END_OF_INCLUDED_FILE_",
	"_DOT_DOT_",
	"_RULE_",
	"_PRIVATE_",
	"_GLOBAL_",
	"_META_",
	"_STRINGS_",
	"_CONDITION_",
	"_IDENTIFIER_",
	"_STRING_IDENTIFIER_",
	"_STRING_COUNT_",
	"_STRING_OFFSET_",
	"_STRING_LENGTH_",
	"_STRING_IDENTIFIER_WITH_WILDCARD_",
	"_NUMBER_",
	"_DOUBLE_",
	"_INTEGER_FUNCTION_",
	"_TEXT_STRING_",
	"_HEX_STRING_",
	"_REGEXP_",
	"_ASCII_",
	"_WIDE_",
	"_XOR_",
	"_NOCASE_",
	"_FULLWORD_",
	"_AT_",
	"_FILESIZE_",
	"_ENTRYPOINT_",
	"_ALL_",
	"_ANY_",
	"_IN_",
	"_OF_",
	"_FOR_",
	"_THEM_",
	"_MATCHES_",
	"_CONTAINS_",
	"_IMPORT_",
	"_TRUE_",
	"_FALSE_",
	"_LBRACE_",
	"_RBRACE_",
	"_INCLUDE_",
	"_OR_",
	"_AND_",
	"'|'",
	"'^'",
	"'&'",
	"_EQ_",
	"_NEQ_",
	"_LT_",
	"_LE_",
	"_GT_",
	"_GE_",
	"_SHIFT_LEFT_",
	"_SHIFT_RIGHT_",
	"'+'",
	"'-'",
	"'*'",
	"'\\\\'",
	"'%'",
	"_NOT_",
	"'~'",
	"UNARY_MINUS",
	"':'",
	"'='",
	"'.'",
	"'['",
	"']'",
	"'('",
	"')'",
	"','",
}
var xxStatenames = [...]string{}

const xxEofCode = 1
const xxErrCode = 2
const xxInitialStackSize = 16

//line /grammar/grammar.y:746

//line yacctab:1
var xxExca = [...]int{
	-1, 1,
	1, -1,
	-2, 15,
	-1, 42,
	24, 34,
	-2, 32,
	-1, 52,
	36, 93,
	-2, 79,
	-1, 107,
	36, 93,
	-2, 79,
	-1, 158,
	74, 50,
	75, 50,
	-2, 53,
	-1, 186,
	74, 51,
	75, 51,
	-2, 53,
}

const xxPrivate = 57344

const xxLast = 405

var xxAct = [...]int{

	52, 183, 108, 140, 49, 146, 159, 172, 73, 53,
	64, 65, 66, 171, 61, 62, 60, 63, 149, 74,
	70, 201, 202, 192, 193, 204, 58, 59, 71, 72,
	80, 79, 54, 112, 113, 198, 114, 50, 51, 96,
	94, 95, 148, 48, 80, 79, 189, 141, 97, 98,
	89, 90, 91, 92, 93, 102, 68, 208, 107, 105,
	56, 69, 106, 42, 194, 109, 195, 111, 57, 115,
	116, 206, 110, 79, 38, 181, 40, 147, 89, 90,
	91, 92, 93, 122, 123, 124, 125, 126, 127, 128,
	129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
	139, 28, 121, 26, 145, 17, 91, 92, 93, 55,
	151, 152, 153, 39, 155, 18, 81, 82, 104, 158,
	80, 79, 161, 162, 164, 160, 96, 94, 95, 87,
	88, 83, 85, 84, 86, 97, 98, 89, 90, 91,
	92, 93, 163, 97, 98, 89, 90, 91, 92, 93,
	165, 150, 73, 5, 64, 65, 66, 142, 61, 62,
	60, 63, 44, 74, 101, 43, 30, 35, 143, 74,
	58, 59, 71, 72, 99, 118, 77, 186, 117, 100,
	187, 13, 8, 184, 190, 46, 47, 185, 154, 7,
	197, 144, 78, 36, 4, 199, 37, 31, 23, 20,
	68, 203, 41, 205, 45, 69, 14, 207, 33, 182,
	25, 73, 103, 64, 65, 66, 22, 61, 62, 60,
	63, 166, 74, 96, 94, 95, 9, 11, 12, 58,
	59, 196, 97, 98, 89, 90, 91, 92, 93, 120,
	96, 94, 95, 175, 174, 178, 176, 177, 167, 97,
	98, 89, 90, 91, 92, 93, 119, 191, 200, 68,
	188, 180, 157, 156, 69, 150, 96, 94, 95, 67,
	76, 103, 75, 32, 27, 97, 98, 89, 90, 91,
	92, 93, 96, 94, 95, 15, 1, 6, 10, 170,
	173, 97, 98, 89, 90, 91, 92, 93, 96, 94,
	95, 179, 34, 24, 29, 169, 21, 97, 98, 89,
	90, 91, 92, 93, 81, 82, 19, 16, 2, 3,
	0, 168, 0, 0, 96, 94, 95, 87, 88, 83,
	85, 84, 86, 97, 98, 89, 90, 91, 92, 93,
	0, 0, 0, 0, 96, 94, 95, 0, 0, 0,
	0, 0, 0, 97, 98, 89, 90, 91, 92, 93,
	96, 94, 95, 0, 0, 0, 0, 0, 0, 97,
	98, 89, 90, 91, 92, 93, 94, 95, 0, 0,
	0, 0, 0, 0, 97, 98, 89, 90, 91, 92,
	93, 95, 0, 0, 0, 0, 0, 0, 97, 98,
	89, 90, 91, 92, 93,
}
var xxPact = [...]int{

	-1000, 148, -1000, -1000, 160, -1000, 219, 159, -1000, 193,
	-1000, -1000, -1000, -1000, -1000, 37, 71, 186, 206, 185,
	-1000, 199, 35, -1000, -1000, 33, 184, 196, 179, 184,
	-1000, 5, 68, 8, 179, -1000, -6, -1000, 143, -1000,
	-5, -1000, 153, -1000, -1000, 173, -1000, -1000, 73, -1000,
	-1000, -1000, 275, 144, 139, 82, -5, -5, -1000, -1000,
	-8, -1000, -1000, -1000, -1000, 1, -4, -37, 198, 198,
	-1000, -1000, -1000, -1000, -1000, 156, 151, -1000, -1000, -1000,
	-1000, 145, 198, 198, 198, 198, 198, 198, 198, 198,
	198, 198, 198, 198, 198, 198, 198, 198, 198, 198,
	-26, 155, 311, 198, 4, -1000, -56, 77, 73, 198,
	198, 198, 175, 198, -5, -1000, -1000, -1000, -1000, -5,
	-5, -1000, 311, 311, 311, 311, 311, 311, 311, 44,
	44, -1000, -1000, -1000, 340, 85, 326, 18, 18, 311,
	-1000, 198, -1000, 89, 4, 191, -1000, -1000, -1000, -1000,
	-1000, 174, 249, 233, -1000, 217, -61, -68, -1000, 218,
	218, -1000, 25, 295, -1000, 7, 169, -1000, -1000, -1000,
	-1000, -1000, -5, -1000, -1000, -1000, -1000, -1000, -1000, 198,
	-27, -1000, -51, -1000, -1000, -1000, -1000, -10, -2, 198,
	-1000, -38, -1000, 169, -1000, -1000, -53, 295, -5, -1000,
	-48, -1000, 198, -3, -5, 311, -1000, -17, -1000,
}
var xxPgo = [...]int{

	0, 319, 318, 317, 316, 306, 304, 166, 303, 302,
	167, 290, 6, 288, 287, 286, 285, 274, 273, 2,
	272, 270, 269, 0, 263, 262, 4, 20, 3, 109,
	261, 260, 258, 5, 257, 256, 239, 231, 221, 209,
	1,
}
var xxR1 = [...]int{

	0, 15, 15, 15, 15, 15, 1, 16, 17, 2,
	5, 5, 8, 8, 18, 14, 14, 13, 13, 3,
	3, 4, 4, 6, 6, 7, 7, 7, 7, 7,
	9, 9, 20, 10, 21, 10, 10, 12, 12, 11,
	11, 11, 11, 11, 22, 22, 22, 22, 24, 24,
	25, 25, 27, 19, 26, 26, 26, 26, 26, 26,
	26, 26, 30, 32, 26, 34, 26, 26, 26, 35,
	26, 36, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 31, 31, 28, 37, 37, 38, 33, 33, 39,
	39, 40, 40, 29, 29, 29, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23,
}
var xxR2 = [...]int{

	0, 0, 2, 2, 3, 2, 2, 0, 0, 11,
	0, 3, 0, 3, 3, 0, 2, 1, 1, 0,
	2, 1, 2, 1, 2, 3, 3, 4, 3, 3,
	1, 2, 0, 5, 0, 5, 3, 0, 2, 1,
	1, 1, 1, 1, 1, 3, 4, 4, 0, 1,
	1, 3, 1, 1, 1, 1, 3, 3, 1, 3,
	3, 3, 0, 0, 11, 0, 9, 3, 2, 0,
	4, 0, 4, 3, 3, 3, 3, 3, 3, 1,
	3, 3, 1, 5, 1, 3, 0, 4, 1, 1,
	3, 1, 1, 1, 1, 1, 3, 1, 1, 4,
	1, 1, 1, 1, 4, 1, 4, 1, 1, 2,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 3,
	3, 1,
}
var xxChk = [...]int{

	-1000, -15, -2, -1, 46, 5, -14, 41, 22, 7,
	-13, 8, 9, 22, 13, -16, -3, 68, 44, -4,
	13, -5, 10, 13, -8, 11, 68, -17, 68, -6,
	-7, 13, -18, 12, -9, -10, 14, -7, 69, 45,
	68, -10, 69, 22, 19, 61, 42, 43, -19, -26,
	42, 43, -23, 14, 37, -29, 65, 73, 31, 32,
	21, 19, 20, 22, 15, 16, 17, -22, 61, 66,
	-27, 33, 34, 13, 24, -20, -21, 23, 19, 48,
	47, 39, 40, 54, 56, 55, 57, 52, 53, 60,
	61, 62, 63, 64, 50, 51, 49, 58, 59, 30,
	35, -29, -23, 73, 36, -19, -26, -23, -19, 73,
	71, 71, 70, 71, 73, -23, -23, 22, 24, -35,
	-36, -27, -23, -23, -23, -23, -23, -23, -23, -23,
	-23, -23, -23, -23, -23, -23, -23, -23, -23, -23,
	-28, 73, 2, 13, 36, -23, -33, 73, 38, 74,
	74, -23, -23, -23, 13, -23, -24, -25, -26, -12,
	-12, -19, -19, -23, 35, -33, -38, 74, 72, 72,
	72, 74, 75, -11, 26, 25, 28, 29, 27, 6,
	-30, 68, -39, -40, 14, 18, -26, -23, -31, 73,
	-28, -34, 74, 75, 74, 68, -37, -23, 73, -40,
	-32, 74, 75, -19, 73, -23, 74, -19, 74,
}
var xxDef = [...]int{

	1, -2, 2, 3, 0, 5, 0, 0, 4, 0,
	16, 17, 18, 6, 7, 19, 0, 0, 10, 20,
	21, 12, 0, 22, 8, 0, 0, 0, 0, 11,
	23, 0, 0, 0, 13, 30, 0, 24, 0, 9,
	0, 31, -2, 25, 26, 0, 28, 29, 14, 53,
	54, 55, -2, 58, 0, 0, 0, 0, 97, 98,
	0, 100, 101, 102, 103, 105, 107, 108, 0, 0,
	121, 94, 95, 44, 52, 0, 0, 36, 27, 69,
	71, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 93, 0, 0, 68, 53, -2, 0, 0,
	0, 0, 0, 0, 48, 109, 118, 37, 37, 0,
	0, 56, 57, 73, 74, 75, 76, 77, 78, 110,
	111, 112, 113, 114, 115, 116, 117, 119, 120, 59,
	60, 0, 61, 0, 0, 0, 67, 86, 88, 80,
	96, 0, 0, 0, 45, 0, 0, 49, -2, 33,
	35, 70, 72, 0, 62, 0, 0, 99, 104, 106,
	46, 47, 0, 38, 39, 40, 41, 42, 43, 0,
	0, 65, 0, 89, 91, 92, -2, 0, 0, 0,
	82, 0, 87, 0, 83, 63, 0, 84, 0, 90,
	0, 81, 0, 0, 0, 85, 66, 0, 64,
}
var xxTok1 = [...]int{

	4, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 64, 51, 3,
	73, 74, 62, 60, 75, 61, 70, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 68, 3,
	3, 69, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 71, 63, 72, 50, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 49, 3, 66,
}
var xxTok2 = [...]int{

	2, 3, 0, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 52, 53, 54,
	55, 56, 57, 58, 59, 65, 67,
}
var xxTok3 = [...]int{
	0,
}

var xxErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	xxDebug        = 0
	xxErrorVerbose = false
)

type xxLexer interface {
	Lex(lval *xxSymType) int
	Error(s string)
}

type xxParser interface {
	Parse(xxLexer) int
	Lookahead() int
}

type xxParserImpl struct {
	lval  xxSymType
	stack [xxInitialStackSize]xxSymType
	char  int
}

func (p *xxParserImpl) Lookahead() int {
	return p.char
}

func xxNewParser() xxParser {
	return &xxParserImpl{}
}

const xxFlag = -1000

func xxTokname(c int) string {
	if c >= 1 && c-1 < len(xxToknames) {
		if xxToknames[c-1] != "" {
			return xxToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func xxStatname(s int) string {
	if s >= 0 && s < len(xxStatenames) {
		if xxStatenames[s] != "" {
			return xxStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func xxErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !xxErrorVerbose {
		return "syntax error"
	}

	for _, e := range xxErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + xxTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := xxPact[state]
	for tok := TOKSTART; tok-1 < len(xxToknames); tok++ {
		if n := base + tok; n >= 0 && n < xxLast && xxChk[xxAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if xxDef[state] == -2 {
		i := 0
		for xxExca[i] != -1 || xxExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; xxExca[i] >= 0; i += 2 {
			tok := xxExca[i]
			if tok < TOKSTART || xxExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if xxExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += xxTokname(tok)
	}
	return res
}

func xxlex1(lex xxLexer, lval *xxSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = xxTok1[0]
		goto out
	}
	if char < len(xxTok1) {
		token = xxTok1[char]
		goto out
	}
	if char >= xxPrivate {
		if char < xxPrivate+len(xxTok2) {
			token = xxTok2[char-xxPrivate]
			goto out
		}
	}
	for i := 0; i < len(xxTok3); i += 2 {
		token = xxTok3[i+0]
		if token == char {
			token = xxTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = xxTok2[1] /* unknown char */
	}
	if xxDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", xxTokname(token), uint(char))
	}
	return char, token
}

func xxParse(xxlex xxLexer) int {
	return xxNewParser().Parse(xxlex)
}

func (xxrcvr *xxParserImpl) Parse(xxlex xxLexer) int {
	var xxn int
	var xxVAL xxSymType
	var xxDollar []xxSymType
	_ = xxDollar // silence set and not used
	xxS := xxrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	xxstate := 0
	xxrcvr.char = -1
	xxtoken := -1 // xxrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		xxstate = -1
		xxrcvr.char = -1
		xxtoken = -1
	}()
	xxp := -1
	goto xxstack

ret0:
	return 0

ret1:
	return 1

xxstack:
	/* put a state and value onto the stack */
	if xxDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", xxTokname(xxtoken), xxStatname(xxstate))
	}

	xxp++
	if xxp >= len(xxS) {
		nyys := make([]xxSymType, len(xxS)*2)
		copy(nyys, xxS)
		xxS = nyys
	}
	xxS[xxp] = xxVAL
	xxS[xxp].yys = xxstate

xxnewstate:
	xxn = xxPact[xxstate]
	if xxn <= xxFlag {
		goto xxdefault /* simple state */
	}
	if xxrcvr.char < 0 {
		xxrcvr.char, xxtoken = xxlex1(xxlex, &xxrcvr.lval)
	}
	xxn += xxtoken
	if xxn < 0 || xxn >= xxLast {
		goto xxdefault
	}
	xxn = xxAct[xxn]
	if xxChk[xxn] == xxtoken { /* valid shift */
		xxrcvr.char = -1
		xxtoken = -1
		xxVAL = xxrcvr.lval
		xxstate = xxn
		if Errflag > 0 {
			Errflag--
		}
		goto xxstack
	}

xxdefault:
	/* default state action */
	xxn = xxDef[xxstate]
	if xxn == -2 {
		if xxrcvr.char < 0 {
			xxrcvr.char, xxtoken = xxlex1(xxlex, &xxrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if xxExca[xi+0] == -1 && xxExca[xi+1] == xxstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			xxn = xxExca[xi+0]
			if xxn < 0 || xxn == xxtoken {
				break
			}
		}
		xxn = xxExca[xi+1]
		if xxn < 0 {
			goto ret0
		}
	}
	if xxn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			xxlex.Error(xxErrorMessage(xxstate, xxtoken))
			Nerrs++
			if xxDebug >= 1 {
				__yyfmt__.Printf("%s", xxStatname(xxstate))
				__yyfmt__.Printf(" saw %s\n", xxTokname(xxtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for xxp >= 0 {
				xxn = xxPact[xxS[xxp].yys] + xxErrCode
				if xxn >= 0 && xxn < xxLast {
					xxstate = xxAct[xxn] /* simulate a shift of "error" */
					if xxChk[xxstate] == xxErrCode {
						goto xxstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if xxDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", xxS[xxp].yys)
				}
				xxp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if xxDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", xxTokname(xxtoken))
			}
			if xxtoken == xxEofCode {
				goto ret1
			}
			xxrcvr.char = -1
			xxtoken = -1
			goto xxnewstate /* try again in the same state */
		}
	}

	/* reduction by production xxn */
	if xxDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", xxn, xxStatname(xxstate))
	}

	xxnt := xxn
	xxpt := xxp
	_ = xxpt // guard against "declared and not used"

	xxp -= xxR2[xxn]
	// xxp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if xxp+1 >= len(xxS) {
		nyys := make([]xxSymType, len(xxS)*2)
		copy(nyys, xxS)
		xxS = nyys
	}
	xxVAL = xxS[xxp+1]

	/* consult goto table to find next state */
	xxn = xxR1[xxn]
	xxg := xxPgo[xxn]
	xxj := xxg + xxS[xxp].yys + 1

	if xxj >= xxLast {
		xxstate = xxAct[xxg]
	} else {
		xxstate = xxAct[xxj]
		if xxChk[xxstate] != -xxn {
			xxstate = xxAct[xxg]
		}
	}
	// dummy call; replaced with literal code
	switch xxnt {

	case 2:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:149
		{
			ParsedRuleset.Rules = append(ParsedRuleset.Rules, xxDollar[2].yr)
		}
	case 3:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:152
		{
			ParsedRuleset.Imports = append(ParsedRuleset.Imports, xxDollar[2].s)
		}
	case 4:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:155
		{
			ParsedRuleset.Includes = append(ParsedRuleset.Includes, xxDollar[3].s)
		}
	case 5:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:158
		{
		}
	case 6:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:164
		{
			xxVAL.s = xxDollar[2].s
		}
	case 7:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:172
		{
			xxVAL.yr.Modifiers = xxDollar[1].rm
			xxVAL.yr.Identifier = xxDollar[3].s

			// Forbid duplicate rules
			for _, r := range ParsedRuleset.Rules {
				if xxDollar[3].s == r.Identifier {
					err := fmt.Errorf(`Duplicate rule "%s"`, xxDollar[3].s)
					panic(err)
				}
			}
		}
	case 8:
		xxDollar = xxS[xxpt-8 : xxpt+1]
//line /grammar/grammar.y:185
		{
			// $4 is the rule created in above action
			xxDollar[4].yr.Tags = xxDollar[5].ss

			// Forbid duplicate tags
			idx := make(map[string]struct{})
			for _, t := range xxDollar[5].ss {
				if _, had := idx[t]; had {
					msg := fmt.Sprintf(`grammar: Rule "%s" has duplicate tag "%s"`,
						xxDollar[4].yr.Identifier,
						t)
					panic(msg)
				}
				idx[t] = struct{}{}
			}

			xxDollar[4].yr.Meta = xxDollar[7].m

			xxDollar[4].yr.Strings = xxDollar[8].yss

			// Forbid duplicate string IDs, except `$` (anonymous)
			idx = make(map[string]struct{})
			for _, s := range xxDollar[8].yss {
				if s.ID == "$" {
					continue
				}
				if _, had := idx[s.ID]; had {
					msg := fmt.Sprintf(
						`grammar: Rule "%s" has duplicated string "%s"`,
						xxDollar[4].yr.Identifier,
						s.ID)
					panic(msg)
				}
				idx[s.ID] = struct{}{}
			}
		}
	case 9:
		xxDollar = xxS[xxpt-11 : xxpt+1]
//line /grammar/grammar.y:222
		{
			c := conditionBuilder.String()
			c = strings.TrimLeft(c, ":\n\r\t ")
			c = strings.TrimRight(c, "}\n\r\t ")
			xxDollar[4].yr.Condition = c
			xxVAL.yr = xxDollar[4].yr
		}
	case 10:
		xxDollar = xxS[xxpt-0 : xxpt+1]
//line /grammar/grammar.y:234
		{

		}
	case 11:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:238
		{
			xxVAL.m = make(data.Metas, 0, len(xxDollar[3].mps))
			for _, mpair := range xxDollar[3].mps {
				// YARA is ok with duplicate keys; we follow suit
				xxVAL.m = append(xxVAL.m, mpair)
			}
		}
	case 12:
		xxDollar = xxS[xxpt-0 : xxpt+1]
//line /grammar/grammar.y:250
		{
			xxVAL.yss = data.Strings{}
		}
	case 13:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:254
		{
			xxVAL.yss = xxDollar[3].yss
		}
	case 15:
		xxDollar = xxS[xxpt-0 : xxpt+1]
//line /grammar/grammar.y:266
		{
			xxVAL.rm = data.RuleModifiers{}
		}
	case 16:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:267
		{
			xxVAL.rm.Private = xxVAL.rm.Private || xxDollar[2].rm.Private
			xxVAL.rm.Global = xxVAL.rm.Global || xxDollar[2].rm.Global
		}
	case 17:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:275
		{
			xxVAL.rm.Private = true
		}
	case 18:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:276
		{
			xxVAL.rm.Global = true
		}
	case 19:
		xxDollar = xxS[xxpt-0 : xxpt+1]
//line /grammar/grammar.y:282
		{
			xxVAL.ss = []string{}
		}
	case 20:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:286
		{
			xxVAL.ss = xxDollar[2].ss
		}
	case 21:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:294
		{
			xxVAL.ss = []string{xxDollar[1].s}
		}
	case 22:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:298
		{
			xxVAL.ss = append(xxDollar[1].ss, xxDollar[2].s)
		}
	case 23:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:306
		{
			xxVAL.mps = data.Metas{xxDollar[1].mp}
		}
	case 24:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:307
		{
			xxVAL.mps = append(xxVAL.mps, xxDollar[2].mp)
		}
	case 25:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:313
		{
			xxVAL.mp = data.Meta{xxDollar[1].s, xxDollar[3].s}
		}
	case 26:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:317
		{
			xxVAL.mp = data.Meta{xxDollar[1].s, xxDollar[3].i64}
		}
	case 27:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:321
		{
			xxVAL.mp = data.Meta{xxDollar[1].s, -xxDollar[4].i64}
		}
	case 28:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:325
		{
			xxVAL.mp = data.Meta{xxDollar[1].s, true}
		}
	case 29:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:329
		{
			xxVAL.mp = data.Meta{xxDollar[1].s, false}
		}
	case 30:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:336
		{
			xxVAL.yss = data.Strings{xxDollar[1].ys}
		}
	case 31:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:337
		{
			xxVAL.yss = append(xxDollar[1].yss, xxDollar[2].ys)
		}
	case 32:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:343
		{
			xxVAL.ys.Type = data.TypeString
			xxVAL.ys.ID = xxDollar[1].s
		}
	case 33:
		xxDollar = xxS[xxpt-5 : xxpt+1]
//line /grammar/grammar.y:348
		{
			xxDollar[3].ys.Text = xxDollar[4].s
			xxDollar[3].ys.Modifiers = xxDollar[5].mod

			xxVAL.ys = xxDollar[3].ys
		}
	case 34:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:355
		{
			xxVAL.ys.Type = data.TypeRegex
			xxVAL.ys.ID = xxDollar[1].s
		}
	case 35:
		xxDollar = xxS[xxpt-5 : xxpt+1]
//line /grammar/grammar.y:360
		{
			xxDollar[3].ys.Text = xxDollar[4].reg.text

			xxDollar[5].mod.I = xxDollar[4].reg.mods.I
			xxDollar[5].mod.S = xxDollar[4].reg.mods.S

			xxDollar[3].ys.Modifiers = xxDollar[5].mod

			xxVAL.ys = xxDollar[3].ys
		}
	case 36:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:371
		{
			xxVAL.ys.Type = data.TypeHexString
			xxVAL.ys.ID = xxDollar[1].s
			xxVAL.ys.Text = xxDollar[3].s
		}
	case 37:
		xxDollar = xxS[xxpt-0 : xxpt+1]
//line /grammar/grammar.y:380
		{
			xxVAL.mod = data.StringModifiers{}
		}
	case 38:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:383
		{
			xxVAL.mod = data.StringModifiers{
				Wide:     xxDollar[1].mod.Wide || xxDollar[2].mod.Wide,
				ASCII:    xxDollar[1].mod.ASCII || xxDollar[2].mod.ASCII,
				Nocase:   xxDollar[1].mod.Nocase || xxDollar[2].mod.Nocase,
				Fullword: xxDollar[1].mod.Fullword || xxDollar[2].mod.Fullword,
				Xor:      xxDollar[1].mod.Xor || xxDollar[2].mod.Xor,
			}
		}
	case 39:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:396
		{
			xxVAL.mod.Wide = true
		}
	case 40:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:397
		{
			xxVAL.mod.ASCII = true
		}
	case 41:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:398
		{
			xxVAL.mod.Nocase = true
		}
	case 42:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:399
		{
			xxVAL.mod.Fullword = true
		}
	case 43:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:400
		{
			xxVAL.mod.Xor = true
		}
	case 44:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:406
		{

		}
	case 45:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:410
		{

		}
	case 46:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:414
		{

		}
	case 47:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:419
		{

		}
	case 48:
		xxDollar = xxS[xxpt-0 : xxpt+1]
//line /grammar/grammar.y:426
		{
		}
	case 49:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:427
		{
		}
	case 50:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:432
		{

		}
	case 51:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:436
		{

		}
	case 52:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:444
		{

		}
	case 53:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:452
		{

		}
	case 54:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:459
		{

		}
	case 55:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:463
		{

		}
	case 56:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:467
		{

		}
	case 57:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:471
		{

		}
	case 58:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:475
		{

		}
	case 59:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:479
		{

		}
	case 60:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:483
		{

		}
	case 61:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:487
		{

		}
	case 62:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:491
		{

		}
	case 63:
		xxDollar = xxS[xxpt-7 : xxpt+1]
//line /grammar/grammar.y:495
		{

		}
	case 64:
		xxDollar = xxS[xxpt-11 : xxpt+1]
//line /grammar/grammar.y:499
		{

		}
	case 65:
		xxDollar = xxS[xxpt-5 : xxpt+1]
//line /grammar/grammar.y:503
		{

		}
	case 66:
		xxDollar = xxS[xxpt-9 : xxpt+1]
//line /grammar/grammar.y:507
		{

		}
	case 67:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:511
		{

		}
	case 68:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:515
		{

		}
	case 69:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:519
		{

		}
	case 70:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:523
		{

		}
	case 71:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:527
		{

		}
	case 72:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:531
		{

		}
	case 73:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:535
		{

		}
	case 74:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:539
		{

		}
	case 75:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:543
		{

		}
	case 76:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:547
		{

		}
	case 77:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:551
		{

		}
	case 78:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:555
		{

		}
	case 79:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:559
		{

		}
	case 80:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:563
		{

		}
	case 81:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:570
		{
		}
	case 82:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:571
		{
		}
	case 83:
		xxDollar = xxS[xxpt-5 : xxpt+1]
//line /grammar/grammar.y:577
		{

		}
	case 84:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:585
		{

		}
	case 85:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:589
		{

		}
	case 86:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:597
		{

		}
	case 88:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:602
		{

		}
	case 91:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:616
		{

		}
	case 92:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:620
		{

		}
	case 94:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:629
		{

		}
	case 95:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:633
		{

		}
	case 96:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:641
		{

		}
	case 97:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:645
		{

		}
	case 98:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:649
		{

		}
	case 99:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:653
		{

		}
	case 100:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:657
		{

		}
	case 101:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:661
		{

		}
	case 102:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:665
		{

		}
	case 103:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:669
		{

		}
	case 104:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:673
		{

		}
	case 105:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:677
		{

		}
	case 106:
		xxDollar = xxS[xxpt-4 : xxpt+1]
//line /grammar/grammar.y:681
		{

		}
	case 107:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:685
		{

		}
	case 108:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:689
		{

		}
	case 109:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:693
		{

		}
	case 110:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:697
		{

		}
	case 111:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:701
		{

		}
	case 112:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:705
		{

		}
	case 113:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:709
		{

		}
	case 114:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:713
		{

		}
	case 115:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:717
		{

		}
	case 116:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:721
		{

		}
	case 117:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:725
		{

		}
	case 118:
		xxDollar = xxS[xxpt-2 : xxpt+1]
//line /grammar/grammar.y:729
		{

		}
	case 119:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:733
		{

		}
	case 120:
		xxDollar = xxS[xxpt-3 : xxpt+1]
//line /grammar/grammar.y:737
		{

		}
	case 121:
		xxDollar = xxS[xxpt-1 : xxpt+1]
//line /grammar/grammar.y:741
		{

		}
	}
	goto xxstack /* stack new state and value */
}
